name: CI
on:
  workflow_dispatch:

env:
  GIT_URL: "${{ github.repository }}.git"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo path
        run: echo ${GIT_URL}
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: docker version
        run: docker -v
      - name: docker build test1
        run: docker build -t test1  -f Dockerfile.a .
      - name: docker build test2
        run: docker build -t test2  -f Dockerfile.b .
      - name: docker test
        run: |
          docker images
          docker run --rm test2 /bin/ls
